#!/bin/bash

treehouses rename treehouses
treehouses expandfs
treehouses button bluetooth

#treehouses wifi <wifiname> [password]
#treehouses ap internet <hotspotname> [password]
treehouses ap internet treehouses
#treehouses ap local <hotspotname> [password]
#treehouses bridge <wifiname> <hotspotname> [wifipassword] [hotspotpassword]

#have internet and wanna latest planet? - please uncomment
#docker pull treehouses/planet:latest
#docker pull treeohuses/planet:db-init
#docker tag treehouses/planet:latest treehouses/planet:local
#docker tag treehouses/planet:db-init treehouses/planet:db-init-local

treehouses tor add 8080

# create kolibri.yml
mkdir -p /srv/kolibri
# cd /srv/kolibri

{
  echo "services:"
  echo "  kolibri:"
  echo "    image: treehouses/kolibri"
  echo "    ports:"
  echo "      - '8080:8080'"
  echo "    volumes:"
  echo "      - '/srv/kolibri:/root/.kolibri'"
  echo "version: '2'"
} > /srv/kolibri/kolibri.yml

# {
#   echo "#!/bin/sh"
#   echo
#   echo "sleep 1"
#   echo
#   echo "docker-compose -f /srv/kolibri/kolibri.yml -p kolibri up -d"
# } > /boot/autorun

# mv /srv/irbilok /srv/kolibri

sync;sync;sync

docker-compose -f /srv/kolibri/kolibri.yml -p kolibri up -d
